- name: task for OS debian
  ansible.builtin.debug:
    msg: "hello debug OS {{vars}}"
    verbosity: 0

- name: shell
  shell: |
    
    pwd
    
    whoami
    
    cat /home/houssou/.ansible
    
    ansible --version
    
    ansible-inventory --list
  register: fileout
  tags: fileout

- debug: msg="{{ fileout.stdout_lines }}"


#- name: Move template terraform
#  copy:
#    src: "templates/terraform"
#    dest: "{{ PATH_REPERTOIR_PLATEFORM }}/{{ PROJET }}/"
#    mode: 0755
#  changed_when: false
