- name: task for OS debian
  ansible.builtin.debug:
    msg: "hello debug OS {{inventory_hostname}}"
    verbosity: 0

- name: shell
  shell: |
    pwd
    whoami

  register: fileout
  tags: fileout

- debug: msg="{{ fileout.stdout_lines }}"


#- name: Move template terraform
#  copy:
#    src: "templates/terraform"
#    dest: "{{ PATH_REPERTOIR_PLATEFORM }}/{{ PROJET }}/"
#    mode: 0755
#  changed_when: false
