- name: task for OS redhat
  ansible.builtin.debug:
    msg: "hello debug OS REDHAT {{inventory_hostname}}"
    verbosity: 0


- name: shell redhat
  shell: |
    pwd
    whoami

  register: fileout
  tags: fileout

- debug: msg="{{ fileout.stdout_lines }}"