
- name: debug
  ansible.builtin.debug:
    msg: "hello debug {{item[0].name}} - {{item[0].hostname}} - {{item[0].group}} - {{item[0].port}}"
    verbosity: 0
  loop: "{{terraform.outputs.cluster_hosts.value}}"

- name: add terraform vagrant master worker01 , worker02 hosts to inventory
  add_host:
    name: '{{item[0].name}}'
    hostname: '{{item[0].name}}'
    ansible_ssh_host: '{{item[0].hostname}}'
    #ansible_ssh_private_key_file: '{{vagrant_cluster_private_key_file}}/{{item[0].name}}/virtualbox/private_key'
    ansible_ssh_port: 22
    ansible_user: vagrant
    groups:
      - 'mycluster_{{item[0].group}}'
  loop: "{{terraform.outputs.cluster_hosts.value}}"
  when: not ansible_check_mode

#- name: export the inventory
#  become: yes
#  become_user: houssou
#  shell: |
#    cd /media/houssou/audrey-roch/Bibind/terraform/marcketplace/plateforme/provider/vagrant/Bibind/cluster
#
#    pwd
#
#    whoami
#
#    ansible-inventory --list --export --output inventory/host.json
#
#  register: inventory_result

- name: Add host in ini file
  delegate_to: localhost
  become: false
  shell: |
    pwd
    cd ./inventory/
    pwd
  register: test

- name: debug retour inventory_hostname
  delegate_to: localhost
  become: false
  ansible.builtin.debug:
    msg: "debug inventory result : {{test}}"
    verbosity: 3


- name: Add host in ini file
  delegate_to: localhost
  become: false
  community.general.ini_file:
    path: ./inventory/hosts
    section: mycluster_master
    option: master
    value: ansible_ssh_host=192.168.56.7  juice
    mode: '0600'
    state: present
    exclusive: false

- name: get ini file
  delegate_to: localhost
  become: false
  shell: |
    cat ./inventory/hosts
  register: hosts_result



- name: debug retour inventory_hostname
  ansible.builtin.debug:
    msg: "debug inventory result : {{hosts_result}}"
    verbosity: 3
#
#- name: debug retour export
#  ansible.builtin.debug:
#    msg: "debug inventory result : {{hostvars}}"
#    verbosity: 3