
- name: debug
  ansible.builtin.debug:
    msg: "hello debug {{path_terraform}}"
    verbosity: 0


#- name: Move template terraform
#  copy:
#    src: "templates/terraform"
#    dest: "{{ PATH_REPERTOIR_PLATEFORM }}/{{ PROJET }}/"
#    mode: 0755
#  changed_when: false

- name: vérifie si le répertoire  projet existe
  stat:
    path: "{{ PATH_REPERTOIR_PLATEFORM }}/{{ PROJET }}/terraform/marcketplace/plateforme/provider/vagrant/Bibind/cluster"
  register: terraform_status



- name: apply terraform code
  cloud.terraform.terraform:
    project_path: "{{ PATH_REPERTOIR_PLATEFORM }}/{{ PROJET }}/terraform/marcketplace/plateforme/provider/vagrant/Bibind/cluster"
    state: present
    force_init: true
  register: terraform
  environment:
    TF_VAR_amount: 3
  when:
  - not ansible_check_mode
  - terraform_status.stat.exists



